abstract: Extract online accounts
author: Kentaro Kuribayashi, <kentaro@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: MIT
name: WWW-Blog-Metadata-AccountAutoDiscovery
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::AccountAutoDiscovery: 0
  WWW::Blog::Metadata: 0
version: 0.03
